name: npm-publish

on:
  push:
    branches:
      - '**'
      - '!master'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
  
    name: npm-publish
    runs-on: ubuntu-latest
    
    permissions: 
      contents: read
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build -- --configuration=production

    # - name: Test
    #   run: npm run test -- --watch=false
