name: npm-publish

on:
  push:
    branches:
      - '**'
      - '!master'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
  
    name: npm-publish
    runs-on: ubuntu-latest
    
    permissions: 
      contents: read
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npx nx run-many -- --target=build --configuration=production

    - name: Test
      run: npx nx run-many -- --target=test --browsers=ChromeHeadless --parallel=true
