name: npm-publish

on:
  push:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write 

jobs:
  build:

    name: npm-publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      packages: write
      attestations: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npx nx run-many --target=build --configuration=production

    - name: Test
      run: npx nx run-many --target=test --browsers=ChromeHeadless --parallel=true

    ## ng-canvas-resizer
    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-ng-canvas-resizer/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-ng-canvas-resizer/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## player-provider
    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-player-provider/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-player-provider/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## player-progress
    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-player-progress/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-player-progress/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## video-player
    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-video-player/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-video-player/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## ng-video-player
    - name: Push to NPM
      id: publish_ng_video_player
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-ng-video-player/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-ng-video-player/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## facebook-player
    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-facebook-player/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-facebook-player/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## mixcloud-player
    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-mixcloud-player/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-mixcloud-player/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## dailymotion-player
    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-dailymotion-player/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-dailymotion-player/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## soundcloud-player
    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-soundcloud-player/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-soundcloud-player/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## spotify-player
    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-spotify-player/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-spotify-player/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## streamable-player
    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-streamable-player/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-streamable-player/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## twitch-player
    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-twitch-player/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-twitch-player/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## vidyard-player
    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-vidyard-player/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-vidyard-player/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## vimeo-player
    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-vimeo-player/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-vimeo-player/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## wistia-player
    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-wistia-player/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-wistia-player/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## youtube-player
    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-youtube-player/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-youtube-player/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## file-player
    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-file-player/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-file-player/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## playlist-controller
    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-playlist-controller/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-playlist-controller/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    # Publish to GitHub Container Registry
    - name: Authenticate with GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Extract tags/labels
      id: meta-ghcr
      uses: docker/metadata-action@v5
      with:
        github-token: ${{ github.token }}
        images: ghcr.io/${{ github.repository }}

    - name: Publish to Github Container Registry
      id: push-ghcr
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta-ghcr.outputs.tags }}
        labels: ${{ steps.meta-ghcr.outputs.labels }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ghcr.io/${{ github.repository }}
        subject-digest: ${{ steps.push-ghcr.outputs.digest }}
        push-to-registry: true

    - name: Trigger deploy hook
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{ secrets.SLIPLANE_DEPLOY_HOOK }}
        method: GET